const ALPHABET_DATABASE = [
  // A (15)
  { letter: "A", item: "Apel", emoji: "🍎", img: "assets/apple.png" },
  { letter: "A", item: "Anggur", emoji: "🍇" },
  { letter: "A", item: "Alpukat", emoji: "🥑" },
  { letter: "A", item: "Awan", emoji: "☁️" },
  { letter: "A", item: "Ayam", emoji: "🐔" },
  { letter: "A", item: "Anjing", emoji: "🐶" },
  { letter: "A", item: "Astronot", emoji: "👨‍🚀" },
  { letter: "A", item: "Ambulans", emoji: "🚑" },
  { letter: "A", item: "Api", emoji: "🔥" },
  { letter: "A", item: "Air", emoji: "💧" },
  { letter: "A", item: "Akar", emoji: "🌱" },
  { letter: "A", item: "Alat tulis", emoji: "✏️" },
  { letter: "A", item: "Antena", emoji: "📡" },
  { letter: "A", item: "Angin", emoji: "🌬️" },
  { letter: "A", item: "Anak", emoji: "🧒" },

  // B (15)
  { letter: "B", item: "Bola", emoji: "⚽", img: "assets/ball.png" },
  { letter: "B", item: "Buku", emoji: "📚" },
  { letter: "B", item: "Bunga", emoji: "🌸" },
  { letter: "B", item: "Bintang", emoji: "⭐" },
  { letter: "B", item: "Bulan", emoji: "🌙" },
  { letter: "B", item: "Bebek", emoji: "🦆" },
  { letter: "B", item: "Beruang", emoji: "🐻" },
  { letter: "B", item: "Bayam", emoji: "🥬" },
  { letter: "B", item: "Bus", emoji: "🚌" },
  { letter: "B", item: "Balon", emoji: "🎈" },
  { letter: "B", item: "Baju", emoji: "👕" },
  { letter: "B", item: "Boneka", emoji: "🧸" },
  { letter: "B", item: "Bubur", emoji: "🥣" },
  { letter: "B", item: "Botol", emoji: "🍼" },
  { letter: "B", item: "Burung", emoji: "🐦" },
  { letter: "B", item: "Buaya", emoji: "🐊", img: "assets/buaya.png" },

  // C (15)
  { letter: "C", item: "Ceri", emoji: "🍒" },
  { letter: "C", item: "Cokelat", emoji: "🍫" },
  { letter: "C", item: "Cermin", emoji: "🪞" },
  { letter: "C", item: "Cangkir", emoji: "☕" },
  { letter: "C", item: "Cabai", emoji: "🌶️" },
  { letter: "C", item: "Cacing", emoji: "🪱" },
  { letter: "C", item: "Cicak", emoji: "🦎" },
  { letter: "C", item: "Celana", emoji: "🩳" },
  { letter: "C", item: "Cumi-cumi", emoji: "🦑" },
  { letter: "C", item: "Cincin", emoji: "💍" },
  { letter: "C", item: "Cangkul", emoji: "⛏️" },
  { letter: "C", item: "Capung", emoji: "🛸" },
  { letter: "C", item: "Catur", emoji: "♟️" },
  { letter: "C", item: "Cat", emoji: "🎨" },
  { letter: "C", item: "Cendrawasih", emoji: "🦜" },

  // D (15)
  { letter: "D", item: "Durian", emoji: "🍈" },
  { letter: "D", item: "Domba", emoji: "🐑" },
  { letter: "D", item: "Dinosaurus", emoji: "🦖" },
  { letter: "D", item: "Dadu", emoji: "🎲" },
  { letter: "D", item: "Dokter", emoji: "🧑‍⚕️" },
  { letter: "D", item: "Donat", emoji: "🍩" },
  { letter: "D", item: "Drum", emoji: "🥁" },
  { letter: "D", item: "Dasi", emoji: "👔" },
  { letter: "D", item: "Daun", emoji: "🍃" },
  { letter: "D", item: "Dapur", emoji: "🍳" },
  { letter: "D", item: "Duit", emoji: "💵" },
  { letter: "D", item: "Duri", emoji: "🌵" },
  { letter: "D", item: "Dermaga", emoji: "⚓" },
  { letter: "D", item: "Delman", emoji: "🐎" },
  { letter: "D", item: "Dinding", emoji: "🧱" },

  // E (15)
  { letter: "E", item: "Elang", emoji: "🦅" },
  { letter: "E", item: "Ember", emoji: "🪣" },
  { letter: "E", item: "Es Krim", emoji: "🍦" },
  { letter: "E", item: "Emas", emoji: "🥇" },
  { letter: "E", item: "Ekor", emoji: "🐒" },
  { letter: "E", item: "Emping", emoji: "🍪" },
  { letter: "E", item: "Engsel", emoji: "🚪" },
  { letter: "E", item: "Eskalator", emoji: "📶" },
  { letter: "E", item: "Eyang", emoji: "🧓" },
  { letter: "E", item: "Enak", emoji: "😋" },
  { letter: "E", item: "Ebi", emoji: "🦐" },
  { letter: "E", item: "Ekspres", emoji: "🚄" },
  { letter: "E", item: "Eksperimen", emoji: "🧪" },
  { letter: "E", item: "Email", emoji: "📧" },
  { letter: "E", item: "Emu", emoji: "🐦" },

  // F (15)
  { letter: "F", item: "Foto", emoji: "📷" },
  { letter: "F", item: "Flamingo", emoji: "🦩" },
  { letter: "F", item: "Fosil", emoji: "🦴" },
  { letter: "F", item: "Feri", emoji: "⛴️" },
  { letter: "F", item: "Futsal", emoji: "⚽" },
  { letter: "F", item: "Fajar", emoji: "🌅" },
  { letter: "F", item: "Fisika", emoji: "⚛️" },
  { letter: "F", item: "Farmasi", emoji: "💊" },
  { letter: "F", item: "Fakel", emoji: "🕯️" },
  { letter: "F", item: "Festival", emoji: "🎡" },
  { letter: "F", item: "Fabel", emoji: "📖" },
  { letter: "F", item: "Finish", emoji: "🏁" },
  { letter: "F", item: "Folder", emoji: "📁" },
  { letter: "F", item: "Flute", emoji: "🪈" },
  { letter: "F", item: "Fokus", emoji: "🔍" },

  // G (15)
  { letter: "G", item: "Gajah", emoji: "🐘", img: "assets/gajah.png" },
  { letter: "G", item: "Gitar", emoji: "🎸" },
  { letter: "G", item: "Gelas", emoji: "🥛" },
  { letter: "G", item: "Gula", emoji: "🍭" },
  { letter: "G", item: "Garam", emoji: "🧂" },
  { letter: "G", item: "Gedung", emoji: "🏢" },
  { letter: "G", item: "Gunting", emoji: "✂️" },
  { letter: "G", item: "Gasing", emoji: "🧶" },
  { letter: "G", item: "Gigi", emoji: "🦷" },
  { letter: "G", item: "Gurita", emoji: "🐙" },
  { letter: "G", item: "Gendang", emoji: "🥁" },
  { letter: "G", item: "Gembok", emoji: "🔒" },
  { letter: "G", item: "Gergaji", emoji: "🪚" },
  { letter: "G", item: "Garpu", emoji: "🍴" },
  { letter: "G", item: "Gunung", emoji: "⛰️" },

  // H (15)
  { letter: "H", item: "Harimau", emoji: "🐯" },
  { letter: "H", item: "Hiu", emoji: "🦈" },
  { letter: "H", item: "Hujan", emoji: "🌧️" },
  { letter: "H", item: "Hutan", emoji: "🌲" },
  { letter: "H", item: "Hadiah", emoji: "🎁" },
  { letter: "H", item: "Handuk", emoji: "🛀" },
  { letter: "H", item: "Helikopter", emoji: "🚁" },
  { letter: "H", item: "Hidung", emoji: "👃" },
  { letter: "H", item: "Hantu", emoji: "👻" },
  { letter: "H", item: "Hati", emoji: "❤️" },
  { letter: "H", item: "Helm", emoji: "🪖" },
  { letter: "H", item: "HP", emoji: "📱" },
  { letter: "H", item: "Hotel", emoji: "🏨" },
  { letter: "H", item: "Hakim", emoji: "👨‍⚖️" },
  { letter: "H", item: "Hormat", emoji: "🫡" },

  // I (15)
  { letter: "I", item: "Ikan", emoji: "🐟" },
  { letter: "I", item: "Itik", emoji: "🦆" },
  { letter: "I", item: "Iguana", emoji: "🦎" },
  { letter: "I", item: "Ibu", emoji: "👩" },
  { letter: "I", item: "Istana", emoji: "🏰" },
  { letter: "I", item: "Ikan Paus", emoji: "🐳" },
  { letter: "I", item: "Ikan Hiu", emoji: "🦈" },
  { letter: "I", item: "Intan", emoji: "💎" },
  { letter: "I", item: "Iglo", emoji: "🧊" },
  { letter: "I", item: "Irama", emoji: "🎵" },
  { letter: "I", item: "Infus", emoji: "💉" },
  { letter: "I", item: "Ikat Pinggang", emoji: "👔" },
  { letter: "I", item: "Idul Fitri", emoji: "🕌" },
  { letter: "I", item: "Imunisasi", emoji: "👶" },
  { letter: "I", item: "Ikan Pari", emoji: "🐟" },

  // J (15)
  { letter: "J", item: "Jagung", emoji: "🌽" },
  { letter: "J", item: "Jerapah", emoji: "🦒", img: "assets/jerapah.png" },
  { letter: "J", item: "Jambu", emoji: "🧧" },
  { letter: "J", item: "Jam", emoji: "⏰" },
  { letter: "J", item: "Jendela", emoji: "🪟" },
  { letter: "J", item: "Jaket", emoji: "🧥" },
  { letter: "J", item: "Jaring", emoji: "🕸️" },
  { letter: "J", item: "Jari", emoji: "🖐️" },
  { letter: "J", item: "Jalan", emoji: "🛣️" },
  { letter: "J", item: "Jembatan", emoji: "🌉" },
  { letter: "J", item: "Jarum", emoji: "🪡" },
  { letter: "J", item: "Jenggot", emoji: "🧔" },
  { letter: "J", item: "Juara", emoji: "🏆" },
  { letter: "J", item: "Jus", emoji: "🥤" },
  { letter: "J", item: "Jangkrik", emoji: "🦗" },

  // K (15)
  { letter: "K", item: "Kelinci", emoji: "🐰" },
  { letter: "K", item: "Kucing", emoji: "🐱", img: "assets/cat.png" },
  { letter: "K", item: "Kuda", emoji: "🐴" },
  { letter: "K", item: "Kura-kura", emoji: "🐢" },
  { letter: "K", item: "Kelapa", emoji: "🥥" },
  { letter: "K", item: "Kunci", emoji: "🔑" },
  { letter: "K", item: "Kursi", emoji: "🪑" },
  { letter: "K", item: "Kamera", emoji: "📷" },
  { letter: "K", item: "Kapal", emoji: "🚢" },
  { letter: "K", item: "Kereta", emoji: "🚂" },
  { letter: "K", item: "Kue", emoji: "🍰" },
  { letter: "K", item: "Kupu-kupu", emoji: "🦋" },
  { letter: "K", item: "Kambing", emoji: "🐐" },
  { letter: "K", item: "Kaki", emoji: "🦶" },
  { letter: "K", item: "Katak", emoji: "🐸", img: "assets/katak.png" },
  { letter: "K", item: "Kuning", emoji: "💛" },

  // L (15)
  { letter: "L", item: "Lumba-lumba", emoji: "🐬" },
  { letter: "L", item: "Lampu", emoji: "💡" },
  { letter: "L", item: "Lebah", emoji: "🐝" },
  { letter: "L", item: "Lidah", emoji: "👅" },
  { letter: "L", item: "Lantai", emoji: "🧱" },
  { letter: "L", item: "Lari", emoji: "🏃" },
  { letter: "L", item: "Layang-layang", emoji: "🪁" },
  { letter: "L", item: "Lemari", emoji: "🗄️" },
  { letter: "L", item: "Lemon", emoji: "🍋" },
  { letter: "L", item: "Lobster", emoji: "🦞" },
  { letter: "L", item: "Langit", emoji: "🌌" },
  { letter: "L", item: "Lilin", emoji: "🕯️" },
  { letter: "L", item: "Lonceng", emoji: "🔔" },
  { letter: "L", item: "Lumpur", emoji: "⛺" },
  { letter: "L", item: "Laba-laba", emoji: "🕷️" },

  // M (15)
  { letter: "M", item: "Monyet", emoji: "🐒", img: "assets/monkey.png" },
  { letter: "M", item: "Mata", emoji: "👁️" },
  { letter: "M", item: "Matahari", emoji: "☀️" },
  { letter: "M", item: "Mobil", emoji: "🚗" },
  { letter: "M", item: "Meja", emoji: "🪑" },
  { letter: "M", item: "Madu", emoji: "🍯" },
  { letter: "M", item: "Mangga", emoji: "🥭" },
  { letter: "M", item: "Manggis", emoji: "🟣" },
  { letter: "M", item: "Masjid", emoji: "🕌" },
  { letter: "M", item: "Mawar", emoji: "🌹" },
  { letter: "M", item: "Melon", emoji: "🍈" },
  { letter: "M", item: "Merpati", emoji: "🕊️" },
  { letter: "M", item: "Minuman", emoji: "🍹" },
  { letter: "M", item: "Mulut", emoji: "👄" },
  { letter: "M", item: "Musik", emoji: "🎵" },

  // N (15)
  { letter: "N", item: "Naga", emoji: "🐉" },
  { letter: "N", item: "Nasi", emoji: "🍚" },
  { letter: "N", item: "Nanas", emoji: "🍍" },
  { letter: "N", item: "Nyamuk", emoji: "🦟" },
  { letter: "N", item: "Nenek", emoji: "👵" },
  { letter: "N", item: "Nilai", emoji: "💯" },
  { letter: "N", item: "Nama", emoji: "🏷️" },
  { letter: "N", item: "Nada", emoji: "🎶" },
  { letter: "N", item: "Neraca", emoji: "⚖️" },
  { letter: "N", item: "Nisan", emoji: "🪦" },
  { letter: "N", item: "Nikel", emoji: "🪙" },
  { letter: "N", item: "Nobel", emoji: "🏅" },
  { letter: "N", item: "Napas", emoji: "🌬️" },
  { letter: "N", item: "Nuklir", emoji: "☢️" },
  { letter: "N", item: "Net", emoji: "🥅" },

  // O (15)
  { letter: "O", item: "Obat", emoji: "💊" },
  { letter: "O", item: "Obeng", emoji: "🪛" },
  { letter: "O", item: "Orang", emoji: "🧑" },
  { letter: "O", item: "Otak", emoji: "🧠" },
  { letter: "O", item: "Obor", emoji: "🔦" },
  { letter: "O", item: "Ondel-ondel", emoji: "🎭" },
  { letter: "O", item: "Oksigen", emoji: "🫧" },
  { letter: "O", item: "Olahraga", emoji: "⛹️" },
  { letter: "O", item: "Omelet", emoji: "🍳" },
  { letter: "O", item: "Opor", emoji: "🍲" },
  { letter: "O", item: "Oskestrasi", emoji: "🎻" },
  { letter: "O", item: "Otot", emoji: "💪" },
  { letter: "O", item: "Oven", emoji: "⏲️" },
  { letter: "O", item: "Oye", emoji: "🤘" },
  { letter: "O", item: "Ocehan", emoji: "🦜" },

  // P (15)
  { letter: "P", item: "Panda", emoji: "🐼", img: "assets/panda.png" },
  { letter: "P", item: "Pisang", emoji: "🍌" },
  { letter: "P", item: "Pesawat", emoji: "✈️" },
  { letter: "P", item: "Pintu", emoji: "🚪" },
  { letter: "P", item: "Payung", emoji: "☂️" },
  { letter: "P", item: "Palu", emoji: "🔨" },
  { letter: "P", item: "Pohon", emoji: "🌳" },
  { letter: "P", item: "Pulpen", emoji: "🖊️" },
  { letter: "P", item: "Pensil", emoji: "✏️" },
  { letter: "P", item: "Piring", emoji: "🍽️" },
  { letter: "P", item: "Polisi", emoji: "👮" },
  { letter: "P", item: "Padi", emoji: "🌾" },
  { letter: "P", item: "Pagar", emoji: "🚧" },
  { letter: "P", item: "Pancing", emoji: "🎣" },
  { letter: "P", item: "Pinguin", emoji: "🐧" },

  // Q (15)
  { letter: "Q", item: "Quran", emoji: "📖" },
  { letter: "Q", item: "Qurban", emoji: "🐄" },
  { letter: "Q", item: "Queen", emoji: "👸" },
  { letter: "Q", item: "Quartz", emoji: "💎" },
  { letter: "Q", item: "Quilt", emoji: "🧵" },
  { letter: "Q", item: "Quiz", emoji: "❓" },
  { letter: "Q", item: "Queue", emoji: "🚶" },
  { letter: "Q", item: "Quick", emoji: "⚡" },
  { letter: "Q", item: "Quiet", emoji: "🤫" },
  { letter: "Q", item: "Quote", emoji: "💬" },
  { letter: "Q", item: "Quartet", emoji: "🎻" },
  { letter: "Q", item: "Query", emoji: "🔍" },
  { letter: "Q", item: "Quokka", emoji: "🐹" },
  { letter: "Q", item: "Quinoa", emoji: "🌾" },
  { letter: "Q", item: "Quality", emoji: "🏅" },

  // R (15)
  { letter: "R", item: "Rusa", emoji: "🦌" },
  { letter: "R", item: "Roti", emoji: "🍞" },
  { letter: "R", item: "Rumah", emoji: "🏠" },
  { letter: "R", item: "Roda", emoji: "🎡" },
  { letter: "R", item: "Rambut", emoji: "💇" },
  { letter: "R", item: "Rantai", emoji: "⛓️" },
  { letter: "R", item: "Raja", emoji: "🤴" },
  { letter: "R", item: "Ratu", emoji: "👸" },
  { letter: "R", item: "Radio", emoji: "📻" },
  { letter: "R", item: "Roket", emoji: "🚀" },
  { letter: "R", item: "Robot", emoji: "🤖" },
  { letter: "R", item: "Rumput", emoji: "🌿" },
  { letter: "R", item: "Rambutan", emoji: "🔴" },
  { letter: "R", item: "Ransel", emoji: "🎒" },
  { letter: "R", item: "Rembulan", emoji: "🌙" },

  // S (15)
  { letter: "S", item: "Sapi", emoji: "🐮" },
  { letter: "S", item: "Singa", emoji: "🦁", img: "assets/lion.png" },
  { letter: "S", item: "Sepeda", emoji: "🚲" },
  { letter: "S", item: "Sepatu", emoji: "👟" },
  { letter: "S", item: "Sendok", emoji: "🥄" },
  { letter: "S", item: "Sabun", emoji: "🧼" },
  { letter: "S", item: "Susu", emoji: "🥛" },
  { letter: "S", item: "Semangka", emoji: "🍉" },
  { letter: "S", item: "Stroberi", emoji: "🍓" },
  { letter: "S", item: "Sumbu", emoji: "🕯️" },
  { letter: "S", item: "Senter", emoji: "🔦" },
  { letter: "S", item: "Siput", emoji: "🐌" },
  { letter: "S", item: "Sisir", emoji: "🪮" },
  { letter: "S", item: "Suling", emoji: "🪈" },
  { letter: "S", item: "Sikat Gigi", emoji: "🪥" },

  // T (15)
  { letter: "T", item: "Tikus", emoji: "🐭" },
  { letter: "T", item: "Topi", emoji: "🧢" },
  { letter: "T", item: "Tas", emoji: "🎒" },
  { letter: "T", item: "Tangan", emoji: "🖐️" },
  { letter: "T", item: "Telur", emoji: "🥚" },
  { letter: "T", item: "Tomat", emoji: "🍅" },
  { letter: "T", item: "Taman", emoji: "🏞️" },
  { letter: "T", item: "Tukang", emoji: "🔨" },
  { letter: "T", item: "Tali", emoji: "🪢" },
  { letter: "T", item: "Tenda", emoji: "⛺" },
  { letter: "T", item: "Telepon", emoji: "☎️" },
  { letter: "T", item: "Televisi", emoji: "📺" },
  { letter: "T", item: "Truk", emoji: "🚚" },
  { letter: "T", item: "Tupai", emoji: "🐿️" },
  { letter: "T", item: "Tanduk", emoji: "🫎" },

  // U (15)
  { letter: "U", item: "Ular", emoji: "🐍" },
  { letter: "U", item: "Uang", emoji: "💵" },
  { letter: "U", item: "Ulat", emoji: "🐛" },
  { letter: "U", item: "Udang", emoji: "🦐" },
  { letter: "U", item: "Ubi", emoji: "🍠" },
  { letter: "U", item: "Ubur-ubur", emoji: "🪼" },
  { letter: "U", item: "Unta", emoji: "🐪" },
  { letter: "U", item: "Ujung", emoji: "📍" },
  { letter: "U", item: "Ukulele", emoji: "🪕" },
  { letter: "U", item: "Ulama", emoji: "👳" },
  { letter: "U", item: "Ulang Tahun", emoji: "🎂" },
  { letter: "U", item: "Uap", emoji: "💨" },
  { letter: "U", item: "Ubin", emoji: "🧱" },
  { letter: "U", item: "Umpan", emoji: "🪱" },
  { letter: "U", item: "Umat", emoji: "👨‍👩‍👧‍👦" },

  // V (15)
  { letter: "V", item: "Vila", emoji: "🏡" },
  { letter: "V", item: "Vas", emoji: "🏺" },
  { letter: "V", item: "Voli", emoji: "🏐" },
  { letter: "V", item: "Video", emoji: "📹" },
  { letter: "V", item: "Vampir", emoji: "🧛" },
  { letter: "V", item: "Vaksin", emoji: "💉" },
  { letter: "V", item: "Vihara", emoji: "🛕" },
  { letter: "V", item: "Vokal", emoji: "🎤" },
  { letter: "V", item: "Vakum", emoji: "🧹" },
  { letter: "V", item: "Vitamin", emoji: "💊" },
  { letter: "V", item: "Variasi", emoji: "♾️" },
  { letter: "V", item: "Viking", emoji: "🛶" },
  { letter: "V", item: "Venesia", emoji: "🚣" },
  { letter: "V", item: "Vonis", emoji: "👨‍⚖️" },
  { letter: "V", item: "Vespa", emoji: "🛵" },

  // W (15)
  { letter: "W", item: "Wortel", emoji: "🥕" },
  { letter: "W", item: "Wayang", emoji: "🎭" },
  { letter: "W", item: "Wadah", emoji: "📦" },
  { letter: "W", item: "Wajah", emoji: "👱" },
  { letter: "W", item: "Wajan", emoji: "🍳" },
  { letter: "W", item: "Waktu", emoji: "⌚" },
  { letter: "W", item: "Wanita", emoji: "👩" },
  { letter: "W", item: "Warna", emoji: "🎨" },
  { letter: "W", item: "Warung", emoji: "🏪" },
  { letter: "W", item: "Wisel", emoji: "🚂" },
  { letter: "W", item: "Waspada", emoji: "⚠️" },
  { letter: "W", item: "Wujud", emoji: "👤" },
  { letter: "W", item: "Warna-warni", emoji: "🌈" },
  { letter: "W", item: "Wiper", emoji: "🚗" },
  { letter: "W", item: "Wajan", emoji: "🍳" },

  // X (15)
  { letter: "X", item: "Xylophone", emoji: "🎹" },
  { letter: "X", item: "X-Ray", emoji: "🩻" },
  { letter: "X", item: "Xerus", emoji: "🐿️" },
  { letter: "X", item: "Xenon", emoji: "💡" },
  { letter: "X", item: "Xenia", emoji: "🚗" },
  { letter: "X", item: "Xylitol", emoji: "🍭" },
  { letter: "X", item: "Xmas", emoji: "🎄" },
  { letter: "X", item: "Xilem", emoji: "🪴" },
  { letter: "X", item: "Xenops", emoji: "🐦" },
  { letter: "X", item: "Xiphias", emoji: "🐟" },
  { letter: "X", item: "Xeric", emoji: "🌵" },
  { letter: "X", item: "Xerox", emoji: "📑" },
  { letter: "X", item: "Xylophone", emoji: "🎹" },
  { letter: "X", item: "Xylophone", emoji: "🎹" },
  { letter: "X", item: "Xanadu", emoji: "🏰" },

  // Y (15)
  { letter: "Y", item: "Yoyo", emoji: "🪀" },
  { letter: "Y", item: "Yogurt", emoji: "🍦" },
  { letter: "Y", item: "Yuyu", emoji: "🦀" },
  { letter: "Y", item: "Yatim", emoji: "👦" },
  { letter: "Y", item: "Yakin", emoji: "🫡" },
  { letter: "Y", item: "Yodium", emoji: "🧂" },
  { letter: "Y", item: "Yoga", emoji: "🧘" },
  { letter: "Y", item: "Yacht", emoji: "🛥️" },
  { letter: "Y", item: "Yummy", emoji: "😋" },
  { letter: "Y", item: "Yudo", emoji: "🥋" },
  { letter: "Y", item: "YouTube", emoji: "📺" },
  { letter: "Y", item: "Yuan", emoji: "💴" },
  { letter: "Y", item: "Yasin", emoji: "📖" },
  { letter: "Y", item: "Yeay", emoji: "🙌" },
  { letter: "Y", item: "Yel", emoji: "📣" },

  // Z (15)
  { letter: "Z", item: "Zebra", emoji: "🦓" },
  { letter: "Z", item: "Zaitun", emoji: "🫒" },
  { letter: "Z", item: "Zirafah", emoji: "🦒" },
  { letter: "Z", item: "Zamrud", emoji: "💎" },
  { letter: "Z", item: "Zakat", emoji: "💰" },
  { letter: "Z", item: "Ziarah", emoji: "🕌" },
  { letter: "Z", item: "Zig-zag", emoji: "📈" },
  { letter: "Z", item: "Zaman", emoji: "⏳" },
  { letter: "Z", item: "Zat", emoji: "🧪" },
  { letter: "Z", item: "Zink", emoji: "🪫" },
  { letter: "Z", item: "Zone", emoji: "📍" },
  { letter: "Z", item: "Zodiak", emoji: "♈" },
  { letter: "Z", item: "Zonk", emoji: "❌" },
  { letter: "Z", item: "Zero", emoji: "0️⃣" },
  { letter: "Z", item: "Zipper", emoji: "🤐" },
];
